"""add auth helper tables

Revision ID: 1284a4fd3465
Revises: b2c3d4e5f6a1
Create Date: 2026-03-02 02:20:11.917578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1284a4fd3465'
down_revision: Union[str, None] = 'b2c3d4e5f6a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply migration changes to database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CM_DeptMaster',
    sa.Column('COMP_CD', sa.Unicode(length=2), nullable=False, comment='법인코드'),
    sa.Column('BUSI_PLACE', sa.Unicode(length=1), nullable=False, comment='사업장코드'),
    sa.Column('DEPT_CODE', sa.Unicode(length=9), nullable=False, comment='부서코드'),
    sa.Column('REAL_DEPT_CODE', sa.Unicode(length=9), nullable=True, comment='실부서코드'),
    sa.Column('DEPT_NAME', sa.Unicode(length=50), nullable=True, comment='부서명_ko(전체)'),
    sa.Column('DEPT_VERSION', sa.Unicode(length=2), nullable=True, comment='부서버전'),
    sa.Column('MAIN_OFFICE', sa.Unicode(length=3), nullable=True, comment='본부'),
    sa.Column('PARENT_DEPT_CODE', sa.Unicode(length=9), nullable=True, comment='상위부서코드'),
    sa.Column('DEPT_NAME_EN', sa.Unicode(length=100), nullable=True, comment='부서명_en'),
    sa.Column('REGION', sa.Unicode(length=2), nullable=True, comment='지역(SY12)'),
    sa.Column('DEPT_TYPE', sa.Unicode(length=2), nullable=True, comment='부서구분(SY13)'),
    sa.Column('PLANT_CODE', sa.Unicode(length=3), nullable=True, comment='공장코드'),
    sa.Column('TERM_FR', sa.DateTime(), nullable=True, comment='기간From'),
    sa.Column('TERM_TO', sa.DateTime(), nullable=True, comment='기간To'),
    sa.Column('PRINT_SEQ', sa.Integer(), nullable=True, comment='출력순서'),
    sa.Column('ACC_TYPE', sa.String(length=1), nullable=True, comment='계정구분'),
    sa.Column('PROD_USE_YN', sa.String(length=1), nullable=True, comment='생산사용여부'),
    sa.Column('CHANGED_DEPT', sa.Unicode(length=9), nullable=True, comment='변경후부서'),
    sa.Column('CHANGED_DATE', sa.DateTime(), nullable=True, comment='변경일자'),
    sa.Column('MGT_CHAR_CODE1', sa.Unicode(length=20), nullable=True, comment='관리문자코드1(부서명)'),
    sa.Column('MGT_CHAR_CODE2', sa.Unicode(length=20), nullable=True, comment='관리문자코드2(영업소_코드-SA01110)'),
    sa.Column('MGT_CHAR_CODE3', sa.Unicode(length=20), nullable=True, comment='관리문자코드3'),
    sa.Column('MGT_NUM_CODE1', sa.Numeric(precision=18, scale=0), nullable=True, comment='관리숫자코드1'),
    sa.Column('MGT_NUM_CODE2', sa.Numeric(precision=18, scale=0), nullable=True, comment='관리숫자코드2'),
    sa.Column('MGT_NUM_CODE3', sa.Numeric(precision=18, scale=0), nullable=True, comment='예산 대상 여부(Y,N)'),
    sa.Column('SECTOR', sa.Unicode(length=2), nullable=True, comment='섹터'),
    sa.Column('PROFIT_PART', sa.Unicode(length=9), nullable=True, comment='이익중심점'),
    sa.Column('BUGT_DIVER_YN', sa.Unicode(length=1), nullable=True, comment='예산전용가능여부'),
    sa.Column('DEPT_GROUP', sa.Unicode(length=3), nullable=True, comment='부서그룹(SY50)'),
    sa.Column('DEPT_CLASS', sa.Unicode(length=3), nullable=True, comment='부서분류(SY52)'),
    sa.Column('IN_DATE', sa.DateTime(), nullable=True, comment='등록 일자'),
    sa.Column('IN_USER', sa.Unicode(length=20), nullable=True, comment='등록자'),
    sa.Column('UP_DATE', sa.DateTime(), nullable=True, comment='수정 일자'),
    sa.Column('UP_USER', sa.Unicode(length=20), nullable=True, comment='수정자'),
    sa.Column('SORT_INFO', sa.Unicode(length=10), nullable=True, comment='정렬순서(0000000)'),
    sa.Column('EXIST_YN', sa.Unicode(length=2), server_default=sa.text("'Y'"), nullable=True, comment='존재여부'),
    sa.PrimaryKeyConstraint('COMP_CD', 'BUSI_PLACE', 'DEPT_CODE', name=op.f('pk_CM_DeptMaster'))
    )
    op.create_table('ST00400',
    sa.Column('USER_ID', sa.Unicode(length=20), nullable=False),
    sa.Column('USER_NAME', sa.Unicode(length=30), nullable=False),
    sa.Column('PASSWORD', sa.Unicode(length=40), nullable=False),
    sa.Column('USER_LEVEL', sa.Unicode(length=2), nullable=True),
    sa.Column('EMP_NO', sa.Unicode(length=20), nullable=True),
    sa.Column('USE_YN', sa.Unicode(length=1), nullable=True),
    sa.Column('EXT_CHAR1', sa.Unicode(length=30), nullable=True),
    sa.Column('EXT_CHAR2', sa.Unicode(length=30), nullable=True),
    sa.Column('EXT_NUM1', sa.Numeric(precision=18, scale=0), nullable=True),
    sa.Column('EXT_NUM2', sa.Numeric(precision=18, scale=0), nullable=True),
    sa.Column('REMARK', sa.Unicode(length=100), nullable=True),
    sa.Column('OUTSIDE_ACCESS_YN', sa.Unicode(length=1), nullable=True),
    sa.Column('LOGIN_FAIL_CNT', sa.Numeric(precision=18, scale=0), nullable=True),
    sa.Column('WEB_STAT', sa.Unicode(length=4), nullable=True),
    sa.PrimaryKeyConstraint('USER_ID', name=op.f('pk_ST00400'))
    )
    op.create_table('TB_ROLE',
    sa.Column('ROLE_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ROLE_CD', sa.Unicode(length=30), nullable=False),
    sa.Column('ROLE_NM', sa.Unicode(length=50), nullable=False),
    sa.Column('ROLE_DESC', sa.Unicode(length=200), nullable=True),
    sa.Column('USE_YN', sa.String(length=1), server_default=sa.text("'Y'"), nullable=False),
    sa.Column('CREATE_DT', sa.DateTime(), server_default=sa.text('GETDATE()'), nullable=False),
    sa.Column('CREATE_USER', sa.Unicode(length=50), server_default=sa.text("'SYSTEM'"), nullable=False),
    sa.Column('UPDATE_DT', sa.DateTime(), nullable=True),
    sa.Column('UPDATE_USER', sa.Unicode(length=50), nullable=True),
    sa.PrimaryKeyConstraint('ROLE_ID', name=op.f('pk_TB_ROLE')),
    sa.UniqueConstraint('ROLE_CD', name=op.f('uq_TB_ROLE_ROLE_CD'))
    )
    op.create_table('connection_tests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connection_tests'))
    )
    op.create_table('TB_LOGIN_LOG',
    sa.Column('LOG_ID', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('USER_ID', sa.Unicode(length=20), nullable=True),
    sa.Column('LOGIN_ID', sa.Unicode(length=50), nullable=False),
    sa.Column('LOGIN_DT', sa.DateTime(), server_default=sa.text('GETDATE()'), nullable=False),
    sa.Column('LOGOUT_DT', sa.DateTime(), nullable=True),
    sa.Column('IP_ADDR', sa.Unicode(length=50), nullable=False),
    sa.Column('USER_AGENT', sa.Unicode(length=500), nullable=True),
    sa.Column('SUCCESS_YN', sa.String(length=1), nullable=False),
    sa.Column('FAIL_REASON', sa.Unicode(length=200), nullable=True),
    sa.ForeignKeyConstraint(['USER_ID'], ['ST00400.USER_ID'], name=op.f('fk_TB_LOGIN_LOG_USER_ID_ST00400')),
    sa.PrimaryKeyConstraint('LOG_ID', name=op.f('pk_TB_LOGIN_LOG'))
    )
    op.create_table('TB_TOKEN_BLACKLIST',
    sa.Column('TOKEN_ID', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('JTI', sa.Unicode(length=100), nullable=False),
    sa.Column('USER_ID', sa.Unicode(length=20), nullable=False),
    sa.Column('ISSUED_DT', sa.DateTime(), nullable=False),
    sa.Column('EXPIRE_DT', sa.DateTime(), nullable=False),
    sa.Column('REVOKE_DT', sa.DateTime(), server_default=sa.text('GETDATE()'), nullable=False),
    sa.Column('REVOKE_REASON', sa.Unicode(length=100), nullable=True),
    sa.ForeignKeyConstraint(['USER_ID'], ['ST00400.USER_ID'], name=op.f('fk_TB_TOKEN_BLACKLIST_USER_ID_ST00400')),
    sa.PrimaryKeyConstraint('TOKEN_ID', name=op.f('pk_TB_TOKEN_BLACKLIST')),
    sa.UniqueConstraint('JTI', name=op.f('uq_TB_TOKEN_BLACKLIST_JTI'))
    )
    op.create_table('TB_USER_ROLE',
    sa.Column('USER_ID', sa.Unicode(length=20), nullable=False),
    sa.Column('ROLE_ID', sa.Integer(), nullable=False),
    sa.Column('GRANT_DT', sa.DateTime(), server_default=sa.text('GETDATE()'), nullable=False),
    sa.Column('GRANT_USER', sa.Unicode(length=50), nullable=False),
    sa.Column('EXPIRE_DT', sa.DateTime(), nullable=True),
    sa.Column('USE_YN', sa.String(length=1), server_default=sa.text("'Y'"), nullable=False),
    sa.ForeignKeyConstraint(['ROLE_ID'], ['TB_ROLE.ROLE_ID'], name=op.f('fk_TB_USER_ROLE_ROLE_ID_TB_ROLE')),
    sa.ForeignKeyConstraint(['USER_ID'], ['ST00400.USER_ID'], name=op.f('fk_TB_USER_ROLE_USER_ID_ST00400')),
    sa.PrimaryKeyConstraint('USER_ID', 'ROLE_ID', name=op.f('pk_TB_USER_ROLE'))
    )
    op.drop_table('TestTable')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration changes from database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TestTable',
    sa.Column('Id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('Name', sa.NVARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('Description', sa.NVARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('CreatedAt', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('Id', name='PK__TestTabl__3214EC07C1D19D3F')
    )
    op.drop_table('TB_USER_ROLE')
    op.drop_table('TB_TOKEN_BLACKLIST')
    op.drop_table('TB_LOGIN_LOG')
    op.drop_table('connection_tests')
    op.drop_table('TB_ROLE')
    op.drop_table('ST00400')
    op.drop_table('CM_DeptMaster')
    # ### end Alembic commands ###
