"""Add CM_BusiPlace table

Revision ID: 1b522f3714ad
Revises: 9edf3e265d79
Create Date: 2026-03-08 08:02:08.657996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b522f3714ad'
down_revision: Union[str, None] = '9edf3e265d79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply migration changes to database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CM_BusiPlace',
    sa.Column('COMP_CD', sa.Unicode(length=2), nullable=False, comment='법인코드'),
    sa.Column('BUSI_PLACE', sa.Unicode(length=1), nullable=False, comment='사업장코드'),
    sa.Column('BUSINESS_NO', sa.Unicode(length=13), nullable=True, comment='사업자번호'),
    sa.Column('BUSI_PLACE_NAME', sa.Unicode(length=50), nullable=True, comment='사업장명_ko'),
    sa.Column('BUSI_PLACE_NAME_EN', sa.Unicode(length=100), nullable=True, comment='사업장명_en'),
    sa.Column('BUSI_PLACE_SHT_NAME', sa.Unicode(length=50), nullable=True, comment='약칭'),
    sa.Column('REP_BUSI_PLACE_YN', sa.String(length=1), nullable=True, comment='대표 사업장 여부'),
    sa.Column('PRESIDENT', sa.Unicode(length=50), nullable=True, comment='대표자_ko'),
    sa.Column('PRESIDENT_EN', sa.Unicode(length=100), nullable=True, comment='대표자_en'),
    sa.Column('BIZ_TYPE', sa.Unicode(length=100), nullable=True, comment='업태'),
    sa.Column('BIZ_ITEM', sa.Unicode(length=100), nullable=True, comment='종목'),
    sa.Column('ZIP_CODE', sa.Unicode(length=6), nullable=True, comment='우편번호'),
    sa.Column('ADDR', sa.Unicode(length=200), nullable=True, comment='주소_ko'),
    sa.Column('ADDR_EN', sa.Unicode(length=300), nullable=True, comment='주소_en'),
    sa.Column('TEL_NO', sa.Unicode(length=25), nullable=True, comment='전화번호'),
    sa.Column('FAX_NO', sa.Unicode(length=25), nullable=True, comment='팩스번호'),
    sa.Column('TAX_OFFICE_CODE', sa.Unicode(length=4), nullable=True, comment='세무서코드'),
    sa.Column('HOMETAX_ID', sa.Unicode(length=10), nullable=True, comment='전자신고UserID'),
    sa.Column('SLAVE_BUSI_NO', sa.Unicode(length=4), nullable=True, comment='단위사업장적용번호'),
    sa.Column('SUM_RECOG_NO', sa.Unicode(length=7), nullable=True, comment='총괄(단위)승인번호'),
    sa.Column('PRSD_SEC_NO', sa.Unicode(length=13), nullable=True, comment='대표자 주민번호'),
    sa.Column('HOMEPAGE', sa.Unicode(length=100), nullable=True, comment='홈페이지'),
    sa.Column('CUST_CODE', sa.Unicode(length=10), nullable=True, comment='사업부문(SY60)'),
    sa.Column('ITEM_CODE', sa.Unicode(length=6), nullable=True, comment='종목 코드'),
    sa.Column('BIZ_DATE', sa.DateTime(), nullable=True, comment='개업 일자'),
    sa.Column('RESI_TX_PLACE', sa.Unicode(length=11), nullable=True, comment='주민세납세지(특수강:사업장기준으로필수)'),
    sa.Column('REMARK', sa.Unicode(length=100), nullable=True, comment='비고'),
    sa.Column('IN_DATE', sa.DateTime(), nullable=True, comment='등록 일자'),
    sa.Column('IN_USER', sa.Unicode(length=20), nullable=True, comment='등록자'),
    sa.Column('UP_DATE', sa.DateTime(), nullable=True, comment='수정 일자'),
    sa.Column('UP_USER', sa.Unicode(length=20), nullable=True, comment='수정자'),
    sa.PrimaryKeyConstraint('COMP_CD', 'BUSI_PLACE', name=op.f('pk_CM_BusiPlace'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration changes from database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CM_BusiPlace')
    # ### end Alembic commands ###
