"""add wb_board_info table

Revision ID: 9edf3e265d79
Revises: 1284a4fd3465
Create Date: 2026-03-02 04:24:02.337163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9edf3e265d79'
down_revision: Union[str, None] = '1284a4fd3465'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply migration changes to database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('WB_BOARD_INFO',
    sa.Column('PROJECT_CD', sa.Unicode(length=10), nullable=False, comment='프로젝트코드'),
    sa.Column('MENU_CD', sa.Unicode(length=5), nullable=False, comment='메뉴코드'),
    sa.Column('BOARD_SEQ', sa.Unicode(length=10), nullable=False, comment='게시물순번'),
    sa.Column('BOARD_TITLE', sa.Unicode(length=250), nullable=True, comment='제목'),
    sa.Column('BOARD_TXT', sa.UnicodeText(), nullable=True, comment='내용'),
    sa.Column('IMPORT_YN', sa.String(length=1), nullable=True, comment='중요여부'),
    sa.Column('POPUP_YN', sa.String(length=1), nullable=True, comment='팝업여부'),
    sa.Column('POPUP_START_DT', sa.Unicode(length=8), nullable=True, comment='팝업시작일'),
    sa.Column('POPUP_END_DT', sa.Unicode(length=8), nullable=True, comment='팝업종료일'),
    sa.Column('BOARD_ATTACH', sa.Unicode(length=36), nullable=True, comment='첨부파일ID'),
    sa.Column('REG_DT', sa.DateTime(), nullable=True, comment='등록일시'),
    sa.Column('REG_CD', sa.Unicode(length=10), nullable=True, comment='등록자코드'),
    sa.Column('MOD_DT', sa.DateTime(), nullable=True, comment='수정일시'),
    sa.Column('MOD_CD', sa.Unicode(length=10), nullable=True, comment='수정자코드'),
    sa.Column('BOARD_CATEGORY', sa.Unicode(length=2), nullable=True, comment='게시물카테고리'),
    sa.Column('WB_BOARD_INFO', sa.Unicode(length=1), nullable=True, comment='게시판정보플래그'),
    sa.PrimaryKeyConstraint('PROJECT_CD', 'MENU_CD', 'BOARD_SEQ', name=op.f('pk_WB_BOARD_INFO'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration changes from database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('TB_USER_ROLE', 'GRANT_DT',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(getdate())'),
               existing_nullable=False)
    op.alter_column('TB_TOKEN_BLACKLIST', 'REVOKE_DT',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(getdate())'),
               existing_nullable=False)
    op.alter_column('TB_ROLE', 'CREATE_DT',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(getdate())'),
               existing_nullable=False)
    op.alter_column('TB_LOGIN_LOG', 'LOGIN_DT',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(getdate())'),
               existing_nullable=False)
    op.drop_table('WB_BOARD_INFO')
    # ### end Alembic commands ###
