"""Add Common Code tables

Revision ID: bfd406d17dd4
Revises: 1b522f3714ad
Create Date: 2026-03-08 08:17:30.743436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfd406d17dd4'
down_revision: Union[str, None] = '1b522f3714ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply migration changes to database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CM_CodeMaster',
    sa.Column('COMP_CD', sa.Unicode(length=2), nullable=False, comment='법인코드'),
    sa.Column('CODE_TYPE', sa.Unicode(length=10), nullable=False, comment='코드구분'),
    sa.Column('CODE_TYPE_NAME', sa.Unicode(length=100), nullable=True, comment='코드구분명'),
    sa.Column('CODE_LENGTH', sa.Integer(), nullable=True, comment='코드길이'),
    sa.Column('MGT_LVL', sa.String(length=1), nullable=True, comment='관리레벨'),
    sa.Column('REMARK', sa.Unicode(length=500), nullable=True, comment='비고'),
    sa.Column('MGT_CHAR1', sa.Unicode(length=100), nullable=True, comment='관리문자1 설명'),
    sa.Column('MGT_CHAR2', sa.Unicode(length=100), nullable=True, comment='관리문자2 설명'),
    sa.Column('MGT_CHAR3', sa.Unicode(length=100), nullable=True, comment='관리문자3 설명'),
    sa.Column('MGT_CHAR4', sa.Unicode(length=100), nullable=True, comment='관리문자4 설명'),
    sa.Column('MGT_NUM1', sa.Unicode(length=100), nullable=True, comment='관리숫자1 설명'),
    sa.Column('MGT_NUM2', sa.Unicode(length=100), nullable=True, comment='관리숫자2 설명'),
    sa.Column('IN_DATE', sa.DateTime(), nullable=True, comment='등록 일자'),
    sa.Column('IN_USER', sa.Unicode(length=20), nullable=True, comment='등록자'),
    sa.Column('UP_DATE', sa.DateTime(), nullable=True, comment='수정 일자'),
    sa.Column('UP_USER', sa.Unicode(length=20), nullable=True, comment='수정자'),
    sa.PrimaryKeyConstraint('COMP_CD', 'CODE_TYPE', name=op.f('pk_CM_CodeMaster'))
    )
    op.create_table('CM_CodeDetail',
    sa.Column('COMP_CD', sa.Unicode(length=2), nullable=False, comment='법인코드'),
    sa.Column('CODE_TYPE', sa.Unicode(length=10), nullable=False, comment='코드구분'),
    sa.Column('CODE', sa.Unicode(length=20), nullable=False, comment='코드'),
    sa.Column('CODE_NAME', sa.Unicode(length=100), nullable=True, comment='코드명'),
    sa.Column('SORT_SEQ', sa.Integer(), nullable=True, comment='정렬순서'),
    sa.Column('USE_YN', sa.String(length=1), nullable=True, comment='사용여부'),
    sa.Column('REMARK', sa.Unicode(length=500), nullable=True, comment='비고'),
    sa.Column('MGT_CHAR1', sa.Unicode(length=50), nullable=True, comment='관리문자1'),
    sa.Column('MGT_CHAR2', sa.Unicode(length=50), nullable=True, comment='관리문자2'),
    sa.Column('MGT_CHAR3', sa.Unicode(length=50), nullable=True, comment='관리문자3'),
    sa.Column('MGT_CHAR4', sa.Unicode(length=50), nullable=True, comment='관리문자4'),
    sa.Column('MGT_CHAR5', sa.Unicode(length=100), nullable=True, comment='관리문자5'),
    sa.Column('MGT_NUM1', sa.Numeric(precision=18, scale=0), nullable=True, comment='관리숫자1'),
    sa.Column('MGT_NUM2', sa.Numeric(precision=18, scale=0), nullable=True, comment='관리숫자2'),
    sa.Column('IN_DATE', sa.DateTime(), nullable=True, comment='등록 일자'),
    sa.Column('IN_USER', sa.Unicode(length=20), nullable=True, comment='등록자'),
    sa.Column('UP_DATE', sa.DateTime(), nullable=True, comment='수정 일자'),
    sa.Column('UP_USER', sa.Unicode(length=20), nullable=True, comment='수정자'),
    sa.ForeignKeyConstraint(['COMP_CD', 'CODE_TYPE'], ['CM_CodeMaster.COMP_CD', 'CM_CodeMaster.CODE_TYPE'], name='fk_CM_CodeDetail_CM_CodeMaster'),
    sa.PrimaryKeyConstraint('COMP_CD', 'CODE_TYPE', 'CODE', name=op.f('pk_CM_CodeDetail'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration changes from database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CM_CodeDetail')
    op.drop_table('CM_CodeMaster')
    # ### end Alembic commands ###
